version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "bot"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"
    groups:
      aws-sdk-dependencies:
        patterns:
          - "*aws-sdk*"
      proxy-agent-dependencies:
        patterns:
          - "*-proxy-agent"
    allow:
      - dependency-type: "production"
    labels:
      - "dependencies"
      - "bot"
